### ISSUE TITLE
Should this be a package or a single-file module?

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/qt-helpers#1]
We could either have this as a mini-package on PyPI, or a single-file module, where the intent is that packages that need it can just bundle it. The use case I have right now is that:

https://github.com/astrofrog/cube-viewer

should be usable without glue installed, which it could do if I used the helpers here.

@ChrisBeaumont - any thoughts?

**Comment by ChrisBeaumont** [comment]
Why not both? There's nothing preventing us from using a single code file + a setup.py file to register on PyPI. I think the only difference is that a naked file gets copied into site-packages instead of a directory. So people could either pip install or easily copy the source file into their project. 

This is what I did for https://github.com/chrisbeaumont/soupy

**Comment by astrofrog** [comment]
Good point! I can try and re-arrange it this way. What do you think about the name? Do you have any better suggestion than `qt-helpers`?

**Comment by ChrisBeaumont** [comment]
qt-helpers sounds good to me!

**Comment by astrofrog** [comment]
Done in d2cf40e9a70788b65769e783c2ac3cc50f8bc825
